### ISSUE TITLE
Content idea: Food options

### ISSUE THREAD

**Issue by hannahbunce** [johnbeech/wedding-website#3]
Detail food options so guests can make a more informed decision about dietary reqs.

**Comment by johnbeech** [comment]
Cool idea, if you could copy and paste the text here, that would help.

**Comment by johnbeech** [comment]
Where is the best place to put the food options?
My first thought was on the Schedule page. 

We could add a new page; but I'm weary of adding a new page because there's limited horizontal space for items on the mobile version of the navigation.

**Comment by hannahbunce** [comment]
Food and drink options:

6 Iten Finger Buffet:
selection of finger sandwiches, sausage rolls, chicken and vegetable skewers, seasonal vegetable quiche, haddock goujons and tartar sauce, mixed leaf salad 

Divine Butchers Choice BBQ:

Italian Rosette Chicken - stuffed chicken breast with bacon, mushrooms and
Dolcelatte cheese
4oz Onglet Steak marinated in smoky BBQ spices
Sea Bass Papillote marinated in lemon, white wine and herbs

Vegetarian Option
Vegetarian Sausage
Roasted vegetables, hummus and halloumi flat bread
Carrot and sesame burger

Your BBQ will be accompanied with seasonal salads, coleslaw and fries so you can
help yourself to the perfect plate.
Drinks Tokens to include (house wine, beer, or house spirit and mixer) £6.50 each

**Comment by johnbeech** [comment]
Done, fixed, implemented, reviewed, uploaded, tested on mobile.
