### ISSUE TITLE
Content idea: List of honeymoon activities as per brochure from travel agent

### ISSUE THREAD

**Issue by hannahbunce** [johnbeech/wedding-website#4]

**Comment by johnbeech** [comment]
I've seen the PDFs; there was an idea to link to the files. Lets match the HTML content as well as described.

**Comment by johnbeech** [comment]
I've updated the registry page with the activities from the brochure; please review:

![image](https://user-images.githubusercontent.com/6341696/60383147-3995be00-9a65-11e9-8064-6c636ad22acd.png)

See:
- https://wedding.hannahjohn2019.wedding/registry

**Comment by johnbeech** [comment]
Done; on branch.
