### ISSUE TITLE
Changes to Wedding registry

### ISSUE THREAD

**Issue by johnbeech** [johnbeech/wedding-website#7]
Original idea:
>Make the wedding registry interactive - display it like a pledge system with items and funding goals .
>
>Allow users to provide their name; and pledge towards the approximate cost of options on the registry.
>
>Record the pledge records similar to RSVP, but make that information public.
>
>Require a name, kept private, so we can clean up spam if need be.

Edited issue to highlight improvements made on the `pledge manager` branch; using a better cleaner layout with more accurate content.

**Comment by hannahbunce** [comment]
Change registry page to include to tables from the Registry Manager without the figures or register functionality.
